#+TITLE: Feynman diagrams
#+AUTHOR: Alexander Huss
#+STARTUP: showall
#+LATEX_HEADER: \usepackage[a4paper]{geometry}
#+LATEX_HEADER: \usepackage{mathtools}


* Introduction
Let's have some fun with Feynman diagrams; we'll use the tool =qgraf= for their generation.
If you want to reproduce the results in this document, you can get the source from here: [[https://cfif.ist.utl.pt/~paulo/qgraf.html][qgraf]] (note that you'll need a =Fortran= compiler for this).

* Drell--Yan
:PROPERTIES:
:header-args: :dir ../../tools/qgraf/dy
:END:

Let's start simple and see how we can generate the diagrams for the Drell--Yan process that we already know.
The example files are located in =../../tools/qgraf/dy= and the program is controlled using the input file =qgraf.dat=.
In this example, the Feynman rules are encoded in a simple model file =dyqcd= and the output style is set by =custom.sty=.
We can run =qgraf= in that directory to generate the diagrams
#+begin_src shell :results output verbatim :exports results
# clean up previous output if it exists
if [[ -f qlist.out ]]; then rm qlist.out; fi
qgraf | tail -n 10
#+end_src

#+RESULTS:
#+begin_example

   #loops    v-degrees          #diagrams

      0
              -   4^1     ....     0
             3^2   -      ....     2


        total =  2 connected diagrams

#+end_example
This will generate the output inside the file =qlist.out=:
#+begin_src shell :exports results :results verbatim
cat qlist.out | awk 'BEGIN{out=0}$1~/^*\*--#\[/{out=1}out==1{print}'
#+end_src

#+RESULTS:
#+begin_example
,*--#[ d1:
,*
 a(1):= (-1)*
  in[-1](quark(p1))*
  in[-3](antiquark(p2))*
 out[-2](l_plus(q1))*
 out[-4](l_minus(q2))*
 prop[1,2](photon(-p1-p2))*
 vrtx[-3,-1,1](antiquark(p2),quark(p1),photon(-p1-p2))*
 vrtx[-4,-2,2](l_plus(-q2),l_minus(-q1),photon(p1+p2));
,*
,*--#] d1:
,*--#[ d2:
,*
 a(2):= (-1)*
  in[-1](quark(p1))*
  in[-3](antiquark(p2))*
 out[-2](l_plus(q1))*
 out[-4](l_minus(q2))*
 prop[1,2](Z(-p1-p2))*
 vrtx[-3,-1,1](antiquark(p2),quark(p1),Z(-p1-p2))*
 vrtx[-4,-2,2](l_plus(-q2),l_minus(-q1),Z(p1+p2));
,*
,*--#] d2:
,*
,* end
,*
#+end_example
which are precisely the two s-channel diagrams we already know for this process.

* Gluon scattering
:PROPERTIES:
:header-args: :dir ../../tools/qgraf/gluons
:END:
We will now consider the case of \(2\to n\) gluon scattering, \(\mathrm{g}\mathrm{g} \to \mathrm{g}\ldots\mathrm{g}\).
To make this more generic, we have a template file from which we generate an input file for =qgraf= to automatically excract the number of diagrams =qgraf= has generated for us.
#+NAME: gluon_diags
#+HEADER: :var ngluons=2 nloop=0
#+begin_src shell :results silent
#> create an input file from the tempalte
out_string=""
sep=""
for i in $(seq 1 ${ngluons}); do
    out_string="${out_string}${sep} gluon"
    sep=","
done
sed -e "s/&out&/${out_string}/g" -e "s/&loops&/${nloop}/g" qgraf.template > qgraf.dat
#> run qgraf and look for the line
#>   `total =  <N> connected diagrams`
#> to extract the number of diagrams qgraf has generated
if [[ -f qlist.out ]]; then rm qlist.out; fi
qgraf | awk '$1~/^total$/&&$(NF)~/^diagrams$/{print $3}'
#+end_src
We can then fill this table for different gluon multiplicities at tree and 1-loop level:
| \(n\) | # diagrams (tree) | # diagrams (1-loop) |
|-------+-------------------+---------------------|
|     2 |                 4 |                 223 |
|     3 |                25 |                2105 |
|     4 |               220 |               25120 |
|     5 |              2485 |              362510 |
#+TBLFM: $2='(org-sbe "gluon_diags" (ngluons $1) (nloop 0))::$3='(org-sbe "gluon_diags" (ngluons $1) (nloop 1))
We can appreciate the rapid increase in the number of diagrams as more legs or loops are added to the diagrams.
Note that this only consitites a very naive estimate for the scaling of the complexity as each individual diagram further becomes more complicated to evalute, especially with each additional loop that involves and additional integration that must be performed.

For the tree diagrams, we can write a very simple recursive formula for the number of diagrams:
\begin{align}
  N_{2\to n}^\text{diags}
  &=
  \mathcal{N}_{n+2}(g,t) \bigr\rvert_{\substack{g=1\\t=1}}
\end{align}
where \(\mathcal{N}_{n+2}(g,t)\) is a polynomial that "counts" the number of gluons and three-gluon vertices for each diagram and can be defined recursively:
\begin{align}
  \mathcal{N}_{m+1}(g,t)
  &= \Bigl(g^3\,t\,\frac{\partial}{\partial g}
         + g\,\frac{\partial}{\partial t} \Bigr)
  \mathcal{N}_{m}(g,t) \,, &
  \mathcal{N}_{3}(g,t) &= g^3\,t
\end{align}
The first term corresponds to an insertion of a new gluon into an existing gluon line, while the second term describes the insertion of a gluon into an existing three-gluon vertex and converting it to a four-gluon vertex.

#+begin_src python :results output verbose :exports both
import sympy
g, t = sympy.symbols('g t')
n_poly = g**3 * t
n_legs = 3
for i in range(10):
    n_poly = sympy.diff(n_poly,g) * g**3 * t + sympy.diff(n_poly,t) * g
    n_legs += 1
    print("{}->{} gluon scattering has {} diagrams".format(2,n_legs-2,n_poly.subs([(g,1),(t,1)])))
#+end_src

#+RESULTS:
#+begin_example
2->2 gluon scattering has 4 diagrams
2->3 gluon scattering has 25 diagrams
2->4 gluon scattering has 220 diagrams
2->5 gluon scattering has 2485 diagrams
2->6 gluon scattering has 34300 diagrams
2->7 gluon scattering has 559405 diagrams
2->8 gluon scattering has 10525900 diagrams
2->9 gluon scattering has 224449225 diagrams
2->10 gluon scattering has 5348843500 diagrams
2->11 gluon scattering has 140880765025 diagrams
#+end_example
